#!/bin/bash

if !(( $# == 1 )); then
    echo "Wrond amount of args!"
    exit -1
fi

if [[ ! -f $1 ]]; then
    echo "Current file doesn't exist!"
    exit -2
fi

mkdir $HOME/.trash && echo "hidden folder created" || echo "hidden folder exists";

ln $1 $HOME/.trash/$RANDOM

echo "deleted path: $PWD/$1 created link: $date" >> $HOME/.trash.log

rm $1